POST  http://localhost:4008/api/v1/brands
content-type: application/json

{
    "name": "fredesd"
}

####

GET http://localhost:4008/api/v1/brands

####

PATCH  http://localhost:4008/api/v1/brands/1
content-type: application/json

{
    "name": "adidas"
}
####

PATCH  http://localhost:4008/api/v1/brands/recovery/1
####

DELETE  http://localhost:4008/api/v1/brands/1


